# Stubs for django.contrib.postgres.fields.ranges (Python 3.5)
#
# This file was generated by stubgen and edited by w0rp.

from typing import Any

from django.db.models import Field


class RangeField(Field):
    empty_strings_allowed = ...  # type: bool

    def get_prep_value(self, value): ...

    def to_python(self, value): ...

    def set_attributes_from_name(self, name): ...

    def value_to_string(self, obj): ...

    def formfield(self, **kwargs): ...


class IntegerRangeField(RangeField):
    base_field = ...  # type: Any
    range_type = ...  # type: Any
    form_field = ...  # type: Any

    def db_type(self, connection): ...


class BigIntegerRangeField(RangeField):
    base_field = ...  # type: Any
    range_type = ...  # type: Any
    form_field = ...  # type: Any

    def db_type(self, connection): ...


class FloatRangeField(RangeField):
    base_field = ...  # type: Any
    range_type = ...  # type: Any
    form_field = ...  # type: Any

    def db_type(self, connection): ...


class DateTimeRangeField(RangeField):
    base_field = ...  # type: Any
    range_type = ...  # type: Any
    form_field = ...  # type: Any

    def db_type(self, connection): ...


class DateRangeField(RangeField):
    base_field = ...  # type: Any
    range_type = ...  # type: Any
    form_field = ...  # type: Any

    def db_type(self, connection): ...
