# Stubs for django.db.models.functions (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import Cast as Cast, Coalesce as Coalesce, Concat as Concat, ConcatPair as ConcatPair, Greatest as Greatest, Least as Least, Length as Length, Lower as Lower, Now as Now, Substr as Substr, Upper as Upper
from .datetime import Extract as Extract, ExtractDay as ExtractDay, ExtractHour as ExtractHour, ExtractMinute as ExtractMinute, ExtractMonth as ExtractMonth, ExtractSecond as ExtractSecond, ExtractWeek as ExtractWeek, ExtractWeekDay as ExtractWeekDay, ExtractYear as ExtractYear, Trunc as Trunc, TruncDate as TruncDate, TruncDay as TruncDay, TruncHour as TruncHour, TruncMinute as TruncMinute, TruncMonth as TruncMonth, TruncSecond as TruncSecond, TruncTime as TruncTime, TruncYear as TruncYear
